[build]
  base = "apps/admin/web"
  command = "NX_SKIP_NX_CLOUD=1 pnpm run build"
  publish = "dist/apps/admin/web"

[build.environment]
  NX_SKIP_NX_CLOUD = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200