[build]
  command = "pnpm --filter web-admin build:staging"
  publish = "dist/apps/web-admin"

[context.staging]
  command = "pnpm --filter web-admin build:staging"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
