# Exported from Render on 2025-12-31T16:36:13Z
version: '1'
projects:
  - name: auth
    environments:
      - name: Production
        services:
          - type: web
            name: celebs
            runtime: docker
            repo: https://github.com/kartos-1993/celebs
            branch: staging
            plan: free
            envVars:
              - key: BASE_PATH
                value: /api/v1
              - key: APP_ORIGIN
                sync: false
              - key: SUPABASE_KEY
                sync: false
              - key: SUPABASE_URL
                sync: false
              - key: NODE_ENV
                sync: false
              - key: PORT
                sync: false
              - key: SMTP_FROM
                sync: false
              - key: SMTP_PASS
                sync: false
              - key: SMTP_USER
                sync: false
              - key: SMTP_PORT
                sync: false
              - key: SMTP_HOST
                sync: false
              - key: JWT_REFRESH_SECRET
                sync: false
              - key: JWT_REFRESH_EXPIRES_IN
                sync: false
              - key: JWT_EXPIRES_IN
                sync: false
              - key: JWT_SECRET
                sync: false
              - key: REDIS_PASSWORD
                sync: false
              - key: REDIS_PORT
                value: "6379"
              - key: REDIS_HOST
                value: promoted-mastodon-182323.upstash.io
              - key: DATABASE_URL
                sync: false
              - key: DIRECT_URL
                sync: false
              - key: MONGODB_URI
                sync: false
              - key: S3_ENDPOINT
                value: https://cba1249fa7c3e183b8e2081761beb0b4.r2.cloudflarestorage.com
              - key: S3_BUCKET_NAME
                value: celebs-media-staging
              - key: S3_REGION
                value: auto
              - key: AWS_ACCESS_KEY_ID
                sync: false
              - key: AWS_SECRET_ACCESS_KEY
                sync: false
              - key: MEDIA_PUBLIC_BASE_URL
                value: https://pub-1b2c37e4039f4ce1982591fe7985a04c.r2.dev
            region: singapore
            dockerContext: .
            dockerfilePath: Dockerfile
            autoDeployTrigger: commit
            rootDir: .
