import { StyleSheet } from 'react-native';

import {
  FontSize,
  FontWeight,
  Palette,
  Radius,
  Spacing,
} from '@/constants/theme';

export const styles = StyleSheet.create({
  triggerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: Palette.accentTint,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: Palette.accent,
    alignSelf: 'flex-start',
    marginVertical: Spacing.xs,
  },
  triggerText: {
    fontSize: FontSize.caption,
    fontWeight: FontWeight.bold,
    color: Palette.accent,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: Palette.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Spacing.xl,
  },
  modalCard: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: Palette.white,
    borderRadius: Radius.xl,
    padding: Spacing.xl,
    shadowColor: Palette.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 8,
    gap: Spacing.md,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitleGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  title: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.extrabold,
    color: Palette.gray900,
  },
  closeBtn: {
    padding: Spacing.xs,
    borderRadius: Radius.sm,
    backgroundColor: Palette.gray100,
  },
  subtitle: {
    fontSize: FontSize.caption,
    color: Palette.gray500,
    lineHeight: 16,
  },
  inputsRow: {
    flexDirection: 'row',
    gap: Spacing.md,
  },
  inputGroup: {
    flex: 1,
    gap: Spacing.xs,
  },
  inputLabel: {
    fontSize: FontSize.footnote,
    fontWeight: FontWeight.bold,
    color: Palette.gray600,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  textInput: {
    backgroundColor: Palette.gray50,
    borderWidth: 1,
    borderColor: Palette.gray300,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    fontSize: FontSize.body,
    fontWeight: FontWeight.semibold,
    color: Palette.gray900,
  },
  fitPillsRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  fitPill: {
    flex: 1,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.md,
    backgroundColor: Palette.gray100,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  fitPillActive: {
    backgroundColor: Palette.accentTint,
    borderColor: Palette.accent,
  },
  fitPillText: {
    fontSize: FontSize.caption,
    fontWeight: FontWeight.semibold,
    color: Palette.gray600,
  },
  fitPillTextActive: {
    color: Palette.accent,
    fontWeight: FontWeight.bold,
  },
  calcButton: {
    backgroundColor: Palette.accent,
    paddingVertical: Spacing.md,
    borderRadius: Radius.md,
    alignItems: 'center',
    marginTop: Spacing.xs,
  },
  calcButtonText: {
    color: Palette.white,
    fontSize: FontSize.small,
    fontWeight: FontWeight.bold,
  },
  resultCard: {
    backgroundColor: Palette.successTint,
    borderWidth: 1,
    borderColor: Palette.success,
    borderRadius: Radius.lg,
    padding: Spacing.lg,
    gap: Spacing.md,
  },
  resultTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  resultLabel: {
    fontSize: FontSize.footnote,
    fontWeight: FontWeight.semibold,
    color: Palette.success,
  },
  resultSize: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.extrabold,
    color: Palette.success,
  },
  confidenceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: Palette.successTint,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderRadius: Radius.sm,
  },
  confidenceText: {
    fontSize: FontSize.footnote,
    fontWeight: FontWeight.bold,
    color: Palette.success,
  },
  applyButton: {
    backgroundColor: Palette.success,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.md,
    alignItems: 'center',
  },
  applyButtonText: {
    color: Palette.white,
    fontSize: FontSize.caption,
    fontWeight: FontWeight.bold,
  },
});
