export enum ErrorCode {
  // General Errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INVALID_REQUEST = 'INVALID_REQUEST',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  FORBIDDEN_ACCESS = 'FORBIDDEN_ACCESS',

  // Auth Specific Errors
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_NOT_FOUND = 'AUTH_NOT_FOUND',
  AUTH_TOO_MANY_ATTEMPTS = 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_TOO_MANY_RESET_ATTEMPTS = 'AUTH_TOO_MANY_RESET_ATTEMPTS',
  AUTH_TOO_MANY_REGISTRATIONS = 'AUTH_TOO_MANY_REGISTRATIONS',
  AUTH_UNAUTHORIZED_ACCESS = 'AUTH_UNAUTHORIZED_ACCESS',
  AUTH_TOKEN_NOT_FOUND = 'AUTH_TOKEN_NOT_FOUND',
  AUTH_PASSWORD_TOO_WEAK = 'AUTH_PASSWORD_TOO_WEAK',
  AUTH_PASSWORD_MISMATCH = 'AUTH_PASSWORD_MISMATCH',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_PERMISSION_DENIED = 'AUTH_PERMISSION_DENIED',

  // Access Control Errors
  ACCESS_FORBIDDEN = 'ACCESS_FORBIDDEN',
  ACCESS_UNAUTHORIZED = 'ACCESS_UNAUTHORIZED',

  // Request Format Errors
  INVALID_REQUEST_FORMAT = 'INVALID_REQUEST_FORMAT',
  INVALID_JSON_FORMAT = 'INVALID_JSON_FORMAT',
  VERIFICATION_ERROR = 'VERIFICATION_ERROR',

  // Category Errors
  CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND',
  CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_UPDATE_FAILED = 'CATEGORY_UPDATE_FAILED',
  CATEGORY_DELETE_FAILED = 'CATEGORY_DELETE_FAILED',

  // Subcategory Errors
  SUBCATEGORY_NOT_FOUND = 'SUBCATEGORY_NOT_FOUND',
  SUBCATEGORY_ALREADY_EXISTS = 'SUBCATEGORY_ALREADY_EXISTS',
  SUBCATEGORY_UPDATE_FAILED = 'SUBCATEGORY_UPDATE_FAILED',
  SUBCATEGORY_DELETE_FAILED = 'SUBCATEGORY_DELETE_FAILED',

  // Product Errors
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_ALREADY_EXISTS = 'PRODUCT_ALREADY_EXISTS',
  PRODUCT_UPDATE_FAILED = 'PRODUCT_UPDATE_FAILED',
  PRODUCT_DELETE_FAILED = 'PRODUCT_DELETE_FAILED',
  PRODUCT_VARIANT_NOT_FOUND = 'PRODUCT_VARIANT_NOT_FOUND',
  PRODUCT_STOCK_INSUFFICIENT = 'PRODUCT_STOCK_INSUFFICIENT',

  // Review Errors
  REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  REVIEW_UPDATE_FAILED = 'REVIEW_UPDATE_FAILED',
  REVIEW_DELETE_FAILED = 'REVIEW_DELETE_FAILED',

  // Media Errors
  MEDIA_UPLOAD_FAILED = 'MEDIA_UPLOAD_FAILED',
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  MEDIA_DELETE_FAILED = 'MEDIA_DELETE_FAILED',
  MEDIA_INVALID_TYPE = 'MEDIA_INVALID_TYPE',
  MEDIA_SIZE_EXCEEDED = 'MEDIA_SIZE_EXCEEDED',

  // Attribute Errors
  ATTRIBUTE_NOT_FOUND = 'ATTRIBUTE_NOT_FOUND',
  ATTRIBUTE_ALREADY_EXISTS = 'ATTRIBUTE_ALREADY_EXISTS',
  ATTRIBUTE_UPDATE_FAILED = 'ATTRIBUTE_UPDATE_FAILED',
  ATTRIBUTE_DELETE_FAILED = 'ATTRIBUTE_DELETE_FAILED',
}
