export enum ErrorCode {
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_NOT_FOUND = 'AUTH_NOT_FOUND',
  AUTH_TOO_MANY_ATTEMPTS = 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_TOO_MANY_RESET_ATTEMPTS = 'AUTH_TOO_MANY_RESET_ATTEMPTS',
  AUTH_TOO_MANY_REGISTRATIONS = 'AUTH_TOO_MANY_REGISTRATIONS',
  AUTH_UNAUTHORIZED_ACCESS = 'AUTH_UNAUTHORIZED_ACCESS',
  AUTH_TOKEN_NOT_FOUND = 'AUTH_TOKEN_NOT_FOUND',
  AUTH_PASSWORD_TOO_WEAK = 'AUTH_PASSWORD_TOO_WEAK',
  AUTH_PASSWORD_MISMATCH = 'AUTH_PASSWORD_MISMATCH',

  // Access Control Errors
  ACCESS_FORBIDDEN = 'ACCESS_FORBIDDEN',
  ACCESS_UNAUTHORIZED = 'ACCESS_UNAUTHORIZED',

  // Validation and Resource Errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INVALID_REQUEST_FORMAT = 'INVALID_REQUEST_FORMAT',
  INVALID_JSON_FORMAT = 'INVALID_JSON_FORMAT',

  // System Errors
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VERIFICATION_ERROR = 'VERIFICATION_ERROR',
}
